"""sync migration

Revision ID: 7eb70405079d
Revises: 20a78951ad71
Create Date: 2025-09-26 09:38:29.112248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7eb70405079d'
down_revision: Union[str, Sequence[str], None] = '20a78951ad71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchases', sa.Column('total_price', sa.Float(), nullable=True))
    op.add_column('purchases', sa.Column('purchase_date', sa.DateTime(), nullable=True))
    op.add_column('purchases', sa.Column('order_id', sa.String(), nullable=True))
    op.alter_column('purchases', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_purchases_order_id'), 'purchases', ['order_id'], unique=True)
    op.drop_column('purchases', 'purchased_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchases', sa.Column('purchased_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_purchases_order_id'), table_name='purchases')
    op.alter_column('purchases', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('purchases', 'order_id')
    op.drop_column('purchases', 'purchase_date')
    op.drop_column('purchases', 'total_price')
    # ### end Alembic commands ###
